version: "3.1"
services:
  node:
    image: "node"
    user: "node"
    working_dir: /home/node/app
    volumes:
      - ./:/home/node/app
    expose:
      - "3000"
    command: "npm start"
    depends_on:
      - mongo
  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: ShoopyApi
      MONGO_INITDB_ROOT_PASSWORD: example
    mongo-express:
      image: mongo-express
      restart: always
      ports:
        - 8081:8081
      environment:
        ME_CONFIG_MONGODB_ADMINUSERNAME: ShoopyApi
        ME_CONFIG_MONGODB_ADMINPASSWORD: example